### ISSUE TITLE
R6 methods are not covered

### ISSUE THREAD

**Issue by abossenbroek** [jimhester/covr#174] opened 2016-05-07 05:08 UTC
I am creating a [package that currently only uses R6 classes](https://github.com/abossenbroek/GeneralTree). When I run 

```
cov <- package_coverage()
str(cov)
```

I get

```
 list()
 - attr(*, "class")= chr "coverage"
 - attr(*, "package")=List of 13
  ..$ package        : chr "GeneralTree"
  ..$ title          : chr "An implementation of a General Tree in R"
  ..$ version        : chr "0.0.0.9000"
  ..$ authors@r      : chr "person(\"Anton\", \"Bossenbroek\", email = \"anton.bossenbroek@me.com\", role = c(\"aut\", \"cre\"))"
  ..$ description    : chr "An implementation of a general tree data structure in R."
  ..$ depends        : chr "R (>= 3.2.5),\nR6 (>= 2.1.2)"
  ..$ license        : chr "MIT + file LICENSE"
  ..$ encoding       : chr "UTF-8"
  ..$ lazydata       : chr "true"
  ..$ suggests       : chr "testthat,\ncovr,\nknitr,\nDiagrammeR"
  ..$ roxygennote    : chr "5.0.1"
  ..$ vignettebuilder: chr "knitr"
  ..$ path           : chr "/Users/anton/Documents/Projects/GeneralTree"
 - attr(*, "relative")= logi TRUE
```

and

```
shine(con)
```

results in,

```
Error in -stats$Relevant : invalid argument to unary operator
```

It looks like all the methods are skipped.

**Comment by jimhester** [comment] 2016-07-07 15:19
Closed by https://github.com/jimhester/covr/commit/7effc3011919befd7fa49f6a7a0b7810c1901349

**Closed by jimhester** 2016-07-07 15:19 UTC
Labels: enhancement

**Comment by smilesun** [comment] 2018-07-05 19:50
does this actually work ?

**Comment by smilesun** [comment] 2018-07-05 20:51
If the child class has method c, which calls father class method a, the a called child class method b. Then B is not covered.

**Comment by jimhester** [comment] 2018-07-05 21:06
Please open a new issue with a reproducible example if you think there is an issue.

**Comment by smilesun** [comment] 2018-07-05 21:54
Hi, I have figured out the coverall site is only displaying commits 2 days ago!! So maybe that is not a problem of covr. Sorry, I will open an issue if after 2 days the coverage is still not consistent to me. Thanks

**Comment by smilesun** [comment] 2018-07-05 21:55
https://coveralls.io/github/smilesun/rlR

**Comment by smilesun** [comment] 2018-07-06 11:42
The delay is caused by `Error: 'from' must be a finite number`
