### ISSUE TITLE
No coverage for C code when tests are executed in parallel

### ISSUE THREAD

**Issue by kforner** [jimhester/covr#227] opened 2016-10-03 13:32 UTC
Hi Jim,

I have made a reproducible example for this issue: https://github.com/kforner/covr_parallel_c_bug
Just get the repo and run make. 

You should get:
For non parallel:

```
covrcparbug Coverage: 100.00%
R/rcode.R: 100.00%
src/ccode.c: 100.00%
```

For parallel:

```
covrcparbug Coverage: 62.50%
src/ccode.c: 0.00%
R/rcode.R: 100.00%
```

which indicates that the coverage of R code works well in parallel (R/rcode.R: 100.00%) but not the coverage of C code src/ccode.c: 0.00% in parallel.

**Comment by jimhester** [comment] 2016-10-03 13:47
I can reproduce your results. I don't think gcov is thread safe, so this will likely never work properly.

**Comment by kforner** [comment] 2016-10-03 13:54
There are not threads here.  mcparallel used fork/join based parallelism. 
I've spotted this post http://stackoverflow.com/questions/14643589/code-coverage-using-gcov-on-parallel-run that seems related. 

Probably gcov would need to be run in a per-process directory. How is gcov run ?

**Comment by jimhester** [comment] 2016-10-03 14:04
Sorry I used the wrong terminology, the main issue is any process would write to the same output files (*.gcno, *gcna). There are based on the source filenames and I don't know of a way to control where they are output. The problem isn't the gcov executable that processes the output, but the compiler instrumentation added when passing `-coverage` to the compiler.

I think it is probably better to just force non-parallel execution when calculating coverage, I don't think this could be resolved without a significant patch to the compiler toolchain.

**Comment by kforner** [comment] 2016-10-03 14:09
Ok, thanks Jim, I'll think about it.

**Closed** 2017-07-23 14:12 UTC
